[general]
import = [
    "~/.config/alacritty/themes/dracula.toml",
]
live_config_reload = true

[env]

[window]
padding.x = 1
padding.y = 1
dynamic_padding = false
decorations = 'None'
startup_mode = 'Maximized'
opacity = 1.0

[scrolling]
history = 20480
multiplier = 3

[font]
normal.family = 'JetBrainsMonoNL NF'
normal.style = 'Regular'
size = 16

[selection]
save_to_clipboard = true

[cursor]
style.shape = 'Block'
style.blinking = 'Always'
vi_mode_style = 'None'
blink_interval = 750

[terminal]
shell.program = '/usr/bin/zsh'
shell.args = [ '-l', ]

[mouse]
hide_when_typing = true
